Read personoppgavehendelser from gcp kafka
navikt/syfooversiktsrv pull request #153
Opened 2022-08-25 11:37 UTC by JMLindseth

2022-08-25 12:56 UTC, geir-waagboe requested changes

2022-08-25 12:56 UTC, geir-waagboe commented on src/main/kotlin/no/nav/syfo/personoppgavehendelse/kafka/PersonoppgavehendelseMetric.kt
> +const val KAFKA_CONSUMER_PERSONOPPGAVEHENDELSE_BASE = "${METRICS_NS}_kafka_consumer_dialogmote_statusendring"
Er verdien riktig her?

2022-08-25 12:56 UTC, geir-waagboe commented on src/main/kotlin/no/nav/syfo/personoppgavehendelse/kafka/PersonoppgavehendelseService.kt
> +        // TODO: vurdere å legge inn støtte for tombstoned records
Ja, er nok lurt å gjøre det (dvs filtrere vekk tombstone-records før prosessering)

2022-08-25 12:56 UTC, geir-waagboe commented on src/main/kotlin/no/nav/syfo/personoppgavehendelse/kafka/PersonoppgavehendelseService.kt
> +            upsertPersonOversiktStatus(
upsert?

2022-08-25 13:04 UTC, juneih commented on src/main/kotlin/no/nav/syfo/personoppgavehendelse/kafka/PersonoppgavehendelseService.kt
> +            upsertPersonOversiktStatus(
update hvis eksisterer, hvis ikke insert = upsert --> https://en.wiktionary.org/wiki/upsert

2022-08-25 13:11 UTC, JMLindseth commented on src/main/kotlin/no/nav/syfo/personoppgavehendelse/kafka/PersonoppgavehendelseService.kt
> +        // TODO: vurdere å legge inn støtte for tombstoned records
Da gjør vi det i en ny oppgave, før ting skrus på 👍

2022-08-26 06:27 UTC, geir-waagboe approved these changes

2022-08-26 06:57 UTC, merged